name: Assistant
main: com.chromaclypse.helper.Helper
version: ${project.version}
description: Better help for players
author: ezeiger92
depend: [ChromaLib]
commands:
    assistant:
        description: Root command
        usage: /assistant [reload]
    guide:
        description: Guide book
        usage: /guide
        permission: helper.guide
permissions:
    helper.reload:
        description: Allows reloading
        default: op
    helper.guide:
        description: Guide command
        default: true
